In [1]:
print("GCP Server Started...")

GCP Server Started...

In [ ]:
## Model training
# clean data - remove missing values, display stats
# encode categorical data
# train XGBoost and randomforest
# save model

In [3]:
import pandas as pd
import numpy as np

In [4]:
# read data

data = pd.read_csv("../data/diabetic_data.csv")

In [5]:
data.head()

,encounter_id,patient_nbr,race,gender,age,weight,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,...,citoglipton,insulin,glyburide-metformin,glipizide-metformin,glimepiride-pioglitazone,metformin-rosiglitazone,metformin-pioglitazone,change,diabetesMed,readmitted
0,2278392,8222157,Caucasian,Female,[0-10),?,6,25,1,1,...,No,No,No,No,No,No,No,No,No,NO
1,149190,55629189,Caucasian,Female,[10-20),?,1,1,7,3,...,No,Up,No,No,No,No,No,Ch,Yes,>30
2,64410,86047875,AfricanAmerican,Female,[20-30),?,1,1,7,2,...,No,No,No,No,No,No,No,No,Yes,NO
3,500364,82442376,Caucasian,Male,[30-40),?,1,1,7,2,...,No,Up,No,No,No,No,No,Ch,Yes,NO
4,16680,42519267,Caucasian,Male,[40-50),?,1,1,7,1,...,No,Steady,No,No,No,No,No,Ch,Yes,NO

In [7]:
data.describe()

,encounter_id,patient_nbr,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,num_lab_procedures,num_procedures,num_medications,number_outpatient,number_emergency,number_inpatient,number_diagnoses
count,1.017660e+05,1.017660e+05,101766.000000,101766.000000,101766.000000,101766.000000,101766.000000,101766.000000,101766.000000,101766.000000,101766.000000,101766.000000,101766.000000
mean,1.652016e+08,5.433040e+07,2.024006,3.715642,5.754437,4.395987,43.095641,1.339730,16.021844,0.369357,0.197836,0.635566,7.422607
std,1.026403e+08,3.869636e+07,1.445403,5.280166,4.064081,2.985108,19.674362,1.705807,8.127566,1.267265,0.930472,1.262863,1.933600
min,1.252200e+04,1.350000e+02,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000
25%,8.496119e+07,2.341322e+07,1.000000,1.000000,1.000000,2.000000,31.000000,0.000000,10.000000,0.000000,0.000000,0.000000,6.000000
50%,1.523890e+08,4.550514e+07,1.000000,1.000000,7.000000,4.000000,44.000000,1.000000,15.000000,0.000000,0.000000,0.000000,8.000000
75%,2.302709e+08,8.754595e+07,3.000000,4.000000,7.000000,6.000000,57.000000,2.000000,20.000000,0.000000,0.000000,1.000000,9.000000
max,4.438672e+08,1.895026e+08,8.000000,28.000000,25.000000,14.000000,132.000000,6.000000,81.000000,42.000000,76.000000,21.000000,16.000000

In [9]:
data.columns

Index(['encounter_id', 'patient_nbr', 'race', 'gender', 'age', 'weight',
       'admission_type_id', 'discharge_disposition_id', 'admission_source_id',
       'time_in_hospital', 'payer_code', 'medical_specialty',
       'num_lab_procedures', 'num_procedures', 'num_medications',
       'number_outpatient', 'number_emergency', 'number_inpatient', 'diag_1',
       'diag_2', 'diag_3', 'number_diagnoses', 'max_glu_serum', 'A1Cresult',
       'metformin', 'repaglinide', 'nateglinide', 'chlorpropamide',
       'glimepiride', 'acetohexamide', 'glipizide', 'glyburide', 'tolbutamide',
       'pioglitazone', 'rosiglitazone', 'acarbose', 'miglitol', 'troglitazone',
       'tolazamide', 'examide', 'citoglipton', 'insulin',
       'glyburide-metformin', 'glipizide-metformin',
       'glimepiride-pioglitazone', 'metformin-rosiglitazone',
       'metformin-pioglitazone', 'change', 'diabetesMed', 'readmitted'],
      dtype='str')

In [34]:
meds = ['metformin', 'repaglinide', 'nateglinide', 'chlorpropamide',
       'glimepiride', 'acetohexamide', 'glipizide', 'glyburide', 'tolbutamide',
       'pioglitazone', 'rosiglitazone', 'acarbose', 'miglitol', 'troglitazone',
       'tolazamide', 'examide', 'citoglipton', 'insulin',
       'glyburide-metformin', 'glipizide-metformin',
       'glimepiride-pioglitazone', 'metformin-rosiglitazone',
       'metformin-pioglitazone']


for m in meds:
    data[f'{m}_bool'] = data[m].apply(lambda x: 0 if x == 'No' else 1)
    data = data.drop(columns=m)

NameError: name 'data' is not defined

In [35]:
print(f"rows: {data.shape[0]} \n columns: {data.shape[1]}")

rows: 101766
 columns: 53

In [14]:
# unique patients
print("---Number of unique patients:---")
data["patient_nbr"].nunique()

---Number of unique patients:---

71518

In [19]:
data["readmitted"].unique()

<StringArray>
['NO', '>30', '<30']
Length: 3, dtype: str

In [ ]:
# target column

data["readmitted_bool"] = data["readmitted"].apply(lambda x: 0 if x=='NO' else 1)

In [22]:
data[["readmitted_bool","readmitted","race"]]

        readmitted_bool readmitted             race
0                     0         NO        Caucasian
1                     1        >30        Caucasian
2                     0         NO  AfricanAmerican
3                     0         NO        Caucasian
4                     0         NO        Caucasian
...                 ...        ...              ...
101761                1        >30  AfricanAmerican
101762                0         NO  AfricanAmerican
101763                0         NO        Caucasian
101764                0         NO        Caucasian
101765                0         NO        Caucasian

[101766 rows x 3 columns]

In [23]:
data.dtypes

encounter_id                int64
patient_nbr                 int64
race                          str
gender                        str
age                           str
weight                        str
admission_type_id           int64
discharge_disposition_id    int64
admission_source_id         int64
time_in_hospital            int64
payer_code                    str
medical_specialty             str
num_lab_procedures          int64
num_procedures              int64
num_medications             int64
number_outpatient           int64
number_emergency            int64
number_inpatient            int64
diag_1                        str
diag_2                        str
diag_3                        str
number_diagnoses            int64
max_glu_serum                 str
A1Cresult                     str
metformin                     str
repaglinide                   str
nateglinide                   str
chlorpropamide                str
glimepiride                   str
acetohexamide                 str
glipizide                     str
glyburide                     str
tolbutamide                   str
pioglitazone                  str
rosiglitazone                 str
acarbose                      str
miglitol                      str
troglitazone                  str
tolazamide                    str
examide                       str
citoglipton                   str
insulin                       str
glyburide-metformin           str
glipizide-metformin           str
glimepiride-pioglitazone      str
metformin-rosiglitazone       str
metformin-pioglitazone        str
change                        str
diabetesMed                   str
readmitted                    str
readmitted_bool             int64
dtype: object

In [54]:
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [30]:
# one-hot-encode the race, age, gender
label_encoder = LabelEncoder()

data["age_label"] = label_encoder.fit_transform(data['age'])
data["gender_bool"] = label_encoder.fit_transform(data['gender'])

In [32]:
data.columns

Index(['encounter_id', 'patient_nbr', 'race', 'gender', 'age', 'weight',
       'admission_type_id', 'discharge_disposition_id', 'admission_source_id',
       'time_in_hospital', 'payer_code', 'medical_specialty',
       'num_lab_procedures', 'num_procedures', 'num_medications',
       'number_outpatient', 'number_emergency', 'number_inpatient', 'diag_1',
       'diag_2', 'diag_3', 'number_diagnoses', 'max_glu_serum', 'A1Cresult',
       'metformin', 'repaglinide', 'nateglinide', 'chlorpropamide',
       'glimepiride', 'acetohexamide', 'glipizide', 'glyburide', 'tolbutamide',
       'pioglitazone', 'rosiglitazone', 'acarbose', 'miglitol', 'troglitazone',
       'tolazamide', 'examide', 'citoglipton', 'insulin',
       'glyburide-metformin', 'glipizide-metformin',
       'glimepiride-pioglitazone', 'metformin-rosiglitazone',
       'metformin-pioglitazone', 'change', 'diabetesMed', 'readmitted',
       'readmitted_bool', 'age_label', 'gender_bool'],
      dtype='str')

In [38]:
data = data.drop(columns=["age","weight","gender","race"])

In [39]:
data.dtypes

encounter_id                     int64
patient_nbr                      int64
admission_type_id                int64
discharge_disposition_id         int64
admission_source_id              int64
time_in_hospital                 int64
payer_code                         str
medical_specialty                  str
num_lab_procedures               int64
num_procedures                   int64
num_medications                  int64
number_outpatient                int64
number_emergency                 int64
number_inpatient                 int64
diag_1                             str
diag_2                             str
diag_3                             str
number_diagnoses                 int64
max_glu_serum                      str
A1Cresult                          str
change                             str
diabetesMed                        str
readmitted                         str
readmitted_bool                  int64
age_label                        int64
gender_bool                      int64
metformin_bool                   int64
repaglinide_bool                 int64
nateglinide_bool                 int64
chlorpropamide_bool              int64
glimepiride_bool                 int64
acetohexamide_bool               int64
glipizide_bool                   int64
glyburide_bool                   int64
tolbutamide_bool                 int64
pioglitazone_bool                int64
rosiglitazone_bool               int64
acarbose_bool                    int64
miglitol_bool                    int64
troglitazone_bool                int64
tolazamide_bool                  int64
examide_bool                     int64
citoglipton_bool                 int64
insulin_bool                     int64
glyburide-metformin_bool         int64
glipizide-metformin_bool         int64
glimepiride-pioglitazone_bool    int64
metformin-rosiglitazone_bool     int64
metformin-pioglitazone_bool      int64
dtype: object

In [40]:
all_features = ['metformin_bool', 'repaglinide_bool',
    'nateglinide_bool', 'chlorpropamide_bool', 'glimepiride_bool',
    'acetohexamide_bool', 'glipizide_bool', 'glyburide_bool',
    'tolbutamide_bool', 'pioglitazone_bool', 'rosiglitazone_bool',
    'acarbose_bool', 'miglitol_bool', 'troglitazone_bool',
    'tolazamide_bool', 'examide_bool', 'citoglipton_bool', 'insulin_bool',
    'glyburide-metformin_bool', 'glipizide-metformin_bool',
    'glimepiride-pioglitazone_bool', 'metformin-rosiglitazone_bool',
    'metformin-pioglitazone_bool','num_lab_procedures', 'num_procedures',
       'num_medications', 'number_outpatient', 'number_emergency',
       'number_inpatient', 'number_diagnoses', 'age_label', 'gender_bool']

0

In [41]:
X = data[all_features]
y = data['readmitted_bool']

### Training with randomforest and xgboost

Random Forest

In [50]:
# split data for train and test 
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [56]:
# initialise classifier

rf = RandomForestClassifier(n_estimators=100, random_state=42)

# fit the train dataset into the model for training
rf.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

In [57]:
# predict and evaluate

y_pred = rf.predict(X_test)
print(f"Accuracy: {accuracy_score(y_test, y_pred):.4f}")

Accuracy: 0.5982

XGBoost

In [59]:
import xgboost as xgb
from xgboost import XGBClassifier

In [61]:
# instantiate classifier

xgb_clf = XGBClassifier(n_estimators=100,
                        learning_rate=0.1,
                        max_depth=5,
                        random_state=42)

In [62]:
# fit classifier to the train dataset

xgb_clf.fit(X_train, y_train)


# make predictions and evaluate
y_pred = xgb_clf.predict(X_test)
print(f"Accuracy: {accuracy_score(y_test, y_pred):.4f}")

Accuracy: 0.6260

In [63]:
# save xgboost model

xgb_clf.save_model('../models/xgboost_model.json')